### ISSUE TITLE
Enhance documentation for SSO (if possible?)

### ISSUE THREAD

**Issue by stevenspasbo** [jeffshurtliff/khoros#40]
Hi,

I'm currently trying to figure out if I can get this library to work with lithium SSO tokens and am a little stuck. It looks like it may be possible though? 

I'm currently working my way through the `khoros.core` and `khoros.auth` modules, but if you have any tips it would be much appreciated.

**Comment by jeffshurtliff** [comment]
This is now available in v4.2.0 which is GA.
