### ISSUE TITLE
Documentation error for define_node_setting

### ISSUE THREAD

**Issue by rzuckerm** [jeffshurtliff/khoros#60]
In [this API documentaion](https://khoros.readthedocs.io/en/latest/core-object-methods.html#khoros.Khoros.Settings.define_node_setting), there are a couple of errors:

1. The default value for `return_json` is `True`, not `False`
2. The function actually returns a `dict` that contains the status of the command -- e.g.:
```json
{
    "staus": "error",
    "error": {
        "code": 100,
        "message": "\\nvalue: This value must be shorter than 10,000 characters in length."
    }
}
```

I didn't discovered this until I tried to update a large custom setting containing the HTML for a board and never saw the board update. I then single-stepped though the `define_node_setting` code and found the above `dict` being returned from that function.

**Comment by jeffshurtliff** [comment]
The fix has been included in v5.1.3 which is now generally available.
